"""
Conversation summarization service.

``SummarizationService`` produces concise summaries of patient–AI
conversations.  Summaries are stored on the ``Conversation`` model and
used as context for subsequent AI prompts, keeping the token window
efficient.

In v1 the service uses a simple extractive approach (taking the first
and last N messages).  In v2 this will be replaced with an LLM-based
abstractive summary generated by a background Celery task.
"""

import logging
from typing import Optional

from ai_assistant.domain.entities.conversation import ConversationEntity, MessageEntity
from ai_assistant.domain.interfaces.repositories import ConversationRepository, MessageRepository
from ai_assistant.exceptions import ConversationNotFoundError

logger = logging.getLogger(__name__)


class SummarizationService:
    """Generate and persist conversation summaries.

    The summary is stored on ``Conversation.summary`` and is included in
    the AI prompt context so the LLM has a condensed history without
    needing the full message list.
    """

    def __init__(
        self,
        conversation_repo: ConversationRepository,
        message_repo: MessageRepository,
    ) -> None:
        self._conversation_repo = conversation_repo
        self._message_repo = message_repo

    def generate_summary(
        self,
        conversation_id: int,
        max_messages: int = 50,
    ) -> str:
        """Build and persist a summary for a conversation.

        Strategy (v1 — extractive):
        1. Fetch the most recent *max_messages* messages.
        2. Concatenate them into a structured summary that captures
           the patient's initial concern, key symptoms, AI advice, and
           current status.

        Strategy (v2 — abstractive):
        3. Replace step 2 with an LLM call that produces a concise,
           clinically-relevant paragraph.

        The summary is saved to ``Conversation.summary`` and also
        returned.
        """
        conversation = self._conversation_repo.get_by_id(conversation_id)
        if conversation is None:
            raise ConversationNotFoundError(f"Conversation {conversation_id} not found.")

        messages = self._message_repo.get_last_n(conversation_id, n=max_messages)
        summary = self._build_extractive_summary(conversation, messages)

        conversation.summary = summary
        self._conversation_repo.save(conversation)

        logger.info("Summary generated for conversation %d (%d chars)", conversation_id, len(summary))
        return summary

    def needs_regeneration(self, conversation: ConversationEntity) -> bool:
        """Determine if the conversation's summary is stale.

        A summary is considered stale if the number of messages since it
        was last generated exceeds a threshold (currently 10 messages).
        """
        if not conversation.summary:
            return True
        if conversation.message_count <= 10:
            return False
        return conversation.message_count > conversation.message_count  # TODO: track last_summary_at

    # ── Private helpers ───────────────────────────────────────────────────

    @staticmethod
    def _build_extractive_summary(
        conversation: ConversationEntity,
        messages: list[MessageEntity],
    ) -> str:
        """Build an extractive summary from the available messages.

        Format:
          Title: <title>
          Status: <status>
          Messages: <count> | Tokens: <total>

          Initial concern: <first user message>
          Key details: <user messages summary>
          AI advice: <assistant messages summary>
          Latest: <last 2 messages>
        """
        if not messages:
            return f"Title: {conversation.title}\nStatus: {conversation.status}\nNo messages yet."

        user_msgs = [m for m in messages if m.role == "user"]
        assistant_msgs = [m for m in messages if m.role == "assistant"]

        header = (
            f"Title: {conversation.title}\n"
            f"Status: {conversation.status}\n"
            f"Messages: {conversation.message_count} | Tokens: {conversation.total_tokens}\n"
        )

        initial_concern = user_msgs[0].content[:200] if user_msgs else ""

        latest = messages[-2:] if len(messages) >= 2 else messages

        lines = [header]
        if initial_concern:
            lines.append(f"Initial concern: {initial_concern}")
        if user_msgs:
            combined_user = " | ".join(m.content[:150] for m in user_msgs[:3])
            lines.append(f"Key details: {combined_user}")
        if assistant_msgs:
            combined_ai = " | ".join(m.content[:150] for m in assistant_msgs[:3])
            lines.append(f"AI advice: {combined_ai}")
        if latest:
            latest_text = " | ".join(f"{m.role}: {m.content[:120]}" for m in latest)
            lines.append(f"Latest: {latest_text}")

        return "\n".join(lines)
