# Generated by Django 4.0.4 on 2024-05-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionFiveQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekend_includes', models.IntegerField(choices=[(1, 'Sunday'), (2, 'Saturday and Sunday')])),
                ('weekend_extra_sleep_duration', models.DurationField(null=True)),
                ('watching_tv_duration', models.DurationField(null=True)),
                ('others_duration', models.DurationField(null=True)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SectionFourQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watching_tv_duration', models.DurationField(null=True)),
                ('chatting_reading_duration', models.DurationField(null=True)),
                ('slow_walking_duration', models.DurationField(null=True)),
                ('shopping_duration', models.DurationField(null=True)),
                ('worship_duration', models.DurationField(null=True)),
                ('playing_musical_instrument_duration', models.DurationField(null=True)),
                ('singing_duration', models.DurationField(null=True)),
                ('others_duration', models.DurationField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SectionOneQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seasonal_activity', models.IntegerField(choices=[(1, 'Yes'), (2, 'No')])),
                ('seasonal_activity_description', models.TextField(blank=True)),
                ('off_seasonal_activity_description', models.TextField(blank=True)),
                ('duration_of_occupation_per_year', models.PositiveIntegerField(null=True)),
                ('seasonal_occupation_months_per_year', models.PositiveIntegerField(null=True)),
                ('off_seasonal_occupation_months_per_year', models.PositiveIntegerField(null=True)),
                ('duration_of_occupation_per_week', models.PositiveIntegerField(null=True)),
                ('seasonal_occupation_days_per_week', models.PositiveIntegerField(null=True)),
                ('off_seasonal_occupation_days_per_week', models.PositiveIntegerField(null=True)),
                ('average_hours_per_day_at_work', models.DurationField(null=True)),
                ('seasonal_occupation_hours_per_day', models.DurationField(null=True)),
                ('off_seasonal_occupation_hours_per_day', models.DurationField(null=True)),
                ('sitting_seasonal_duration', models.DurationField(null=True)),
                ('sitting_off_seasonal_duration', models.DurationField(null=True)),
                ('standing_seasonal_duration', models.DurationField(null=True)),
                ('standing_off_seasonal_duration', models.DurationField(null=True)),
                ('walking_seasonal_duration', models.DurationField(null=True)),
                ('walking_off_seasonal_duration', models.DurationField(null=True)),
                ('climbing_seasonal_duration', models.DurationField(null=True)),
                ('climbing_off_seasonal_duration', models.DurationField(null=True)),
                ('skilled_activities_seasonal_duration', models.DurationField(null=True)),
                ('skilled_activities_off_seasonal_duration', models.DurationField(null=True)),
                ('strenuous_activities_seasonal_duration', models.DurationField(null=True)),
                ('strenuous_activities_off_seasonal_duration', models.DurationField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SectionThreeQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_driving_duration', models.DurationField(null=True)),
                ('commuting_duration', models.DurationField(null=True)),
                ('cycling_duration', models.DurationField(null=True)),
                ('walking_duration', models.DurationField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SectionTwoQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_sleep_and_nap', models.DurationField(null=True)),
                ('personal_care_duration', models.DurationField(null=True)),
                ('cooking_duration', models.DurationField(null=True)),
                ('collecting_water_wood_duration', models.DurationField(null=True)),
                ('non_mechanized_domestic_chores_duration', models.DurationField(null=True)),
                ('climbing_steps_duration', models.DurationField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='activity_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('c', 'Walking'), ('d', 'Climbing'), ('e', 'Skilled'), ('f', 'Strenuous')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='duration_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='duration_weeks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='duration_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='hours_per_day',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='is_full_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='is_seasonal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='question_code',
            field=models.CharField(choices=[('1', 'Does your work involve Seasonal Activity?'), ('2', 'Specify Seasonal / Primary or Full Time Activity / Occupation'), ('3', 'Specify Off-Seasonal / Part-time Activity / Occupation'), ('4a', 'Indicate your duration of occupation per year'), ('4b', 'Seasonal Occupation / Full Time Months / Year'), ('4c', 'Off-Seasonal Occupation / Part-Time Months / Year'), ('5a', 'Indicate your duration of occupation per Week'), ('5b', 'Seasonal Occupation / Full Time Days / Week'), ('5c', 'Off-Seasonal Occupation / Part-Time Days / Week'), ('6a', 'On an average, how many hours per day do you spend at work place?'), ('6b', 'Seasonal Occupation / Full Time Hours : Minutes / Day'), ('6c', 'Off-Seasonal Occupation / Part-Time Hours : Minutes / Day'), ('7', 'At the work place, how many hours per day do you spend on the following:'), ('7a', 'Sitting (Office Work)'), ('7g', 'Sitting (Office Work)'), ('7b', 'Standing'), ('7h', 'Standing'), ('7c', 'Walking at varying paces without a load'), ('7i', 'Walking at varying paces without a load'), ('7d', 'Climbing stairs / Walking uphill'), ('7j', 'Climbing stairs / Walking uphill'), ('7e', 'Skilled occupational activities - [professional Babysitting –Crèche; driving, tailoring, Laundering, housekeeping etc.,]'), ('7k', 'Skilled occupational activities - [professional Babysitting –Crèche; driving, tailoring, Laundering, housekeeping, etc.,]'), ('7f', 'An activity more strenuous than walking'), ('7l', 'An activity more strenuous than walking'), ('8', 'Sleeping (Regular hours of sleep usually at night) plus Nap (short sleep - day time)'), ('9', 'Personal care - brushing, Toilet, Showering, Dressing, Hair dressing and Eating (Include all meals, snacks & coffee/tea drinks)'), ('10', 'Cooking – (including Pre-preparation of meals, snacks and beverages)'), ('11', 'Collecting water/ wood'), ('12', 'Non-mechanized domestic chores (sweeping, washing clothes and dishes by hand, baby care, elderly care)'), ('13', 'Climbing steps / walking uphill'), ('14', 'Self driving – work and other places (car/bike/scooter)'), ('15', 'Commuting by bus / auto / pillion rider (to work & other places)'), ('16', 'Travel by cycling (excludes cycling as an exercise)'), ('17', 'Walking to and fro places (excludes walking as an exercise)'), ('18a', 'Watching TV'), ('18b', 'Chatting, reading, sitting, listening to music, etc.'), ('18c', 'Slow walking'), ('18d', 'Shopping'), ('18e', 'Going to a worship place'), ('18f', 'Playing a musical Instrument'), ('18g', 'Singing (as a hobby)'), ('18h', 'Others'), ('19', 'Week end includes? Sunday 1, Saturday and Sunday 2'), ('20', 'Weekend extra night sleep / Nap'), ('21', 'List all the extra activities that you do in a typical weekend and are not mentioned in the earlier sections'), ('22', 'Others'), ('23', 'Comments, (if any)')], default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.CharField(choices=[('I', 'Physical Activity at Work'), ('II', 'Physical Activity – General'), ('III', 'Physical Activity - Commutation (Transport)'), ('IV', 'Physical Activity - Recreation'), ('V', 'Physical Activity - Weekend Recreation')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
