# Generated by Django 4.0.4 on 2024-05-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_sectionfivequestions_sectionfourquestions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='health_status',
            field=models.CharField(choices=[('weight', 'Weight'), ('bmi', 'BMI'), ('bp', 'BP'), ('diastolic', 'Diastolic')], max_length=15),
        ),
    ]
