# Generated by Django 4.0.4 on 2024-05-20 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_health_status_patient_patient_health_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patient_health_status',
            new_name='health_status',
        ),
    ]
