# Generated by Django 4.0.4 on 2024-05-20 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0014_rename_patient_health_status_patient_health_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectiononequestions',
            name='average_hours_per_day_at_work',
        ),
        migrations.RemoveField(
            model_name='sectiononequestions',
            name='climbing_off_seasonal_duration',
        ),
        migrations.RemoveField(
            model_name='sectiononequestions',
            name='climbing_seasonal_duration',
        ),
        migrations.RemoveField(
            model_name='sectiononequestions',
            name='duration_of_occupation_per_week',
        ),
        migrations.RemoveField(
            model_name='sectiononequestions',
            name='duration_of_occupation_per_year',
        ),
        migrations.RemoveField(
            model_name='sectiononequestions',
            name='off_seasonal_activity_description',
        ),
        migrations.RemoveField(
            model_name='sectiononequestions',
            name='off_seasonal_occupation_days_per_week',
        ),
        migrations.RemoveField(
            model_name='sectiononequestions',
            name='off_seasonal_occupation_hours_per_day',
        ),
        migrations.RemoveField(
            model_name='sectiononequestions',
            name='off_seasonal_occupation_months_per_year',
        ),
        migrations.RemoveField(
            model_name='sectiononequestions',
            name='seasonal_activity',
        ),
        migrations.RemoveField(
            model_name='sectiononequestions',
            name='seasonal_activity_description',
        ),
        migrations.RemoveField(
            model_name='sectiononequestions',
            name='seasonal_occupation_days_per_week',
        ),
        migrations.RemoveField(
            model_name='sectiononequestions',
            name='seasonal_occupation_hours_per_day',
        ),
        migrations.RemoveField(
            model_name='sectiononequestions',
            name='seasonal_occupation_months_per_year',
        ),
        migrations.RemoveField(
            model_name='sectiononequestions',
            name='sitting_off_seasonal_duration',
        ),
        migrations.RemoveField(
            model_name='sectiononequestions',
            name='sitting_seasonal_duration',
        ),
        migrations.RemoveField(
            model_name='sectiononequestions',
            name='skilled_activities_off_seasonal_duration',
        ),
        migrations.RemoveField(
            model_name='sectiononequestions',
            name='skilled_activities_seasonal_duration',
        ),
        migrations.RemoveField(
            model_name='sectiononequestions',
            name='standing_off_seasonal_duration',
        ),
        migrations.RemoveField(
            model_name='sectiononequestions',
            name='standing_seasonal_duration',
        ),
        migrations.RemoveField(
            model_name='sectiononequestions',
            name='strenuous_activities_off_seasonal_duration',
        ),
        migrations.RemoveField(
            model_name='sectiononequestions',
            name='strenuous_activities_seasonal_duration',
        ),
        migrations.RemoveField(
            model_name='sectiononequestions',
            name='walking_off_seasonal_duration',
        ),
        migrations.RemoveField(
            model_name='sectiononequestions',
            name='walking_seasonal_duration',
        ),
        migrations.AddField(
            model_name='sectionfivequestions',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sectionfourquestions',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sectiononequestions',
            name='climbing_stairs_full_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectiononequestions',
            name='climbing_stairs_part_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectiononequestions',
            name='duration_occupation_week_full_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectiononequestions',
            name='duration_occupation_week_part_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectiononequestions',
            name='duration_occupation_year_full_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectiononequestions',
            name='duration_occupation_year_part_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectiononequestions',
            name='hours_per_day_full_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectiononequestions',
            name='hours_per_day_part_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectiononequestions',
            name='off_seasonal_activity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sectiononequestions',
            name='primary_activity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sectiononequestions',
            name='sitting_full_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectiononequestions',
            name='sitting_part_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectiononequestions',
            name='skilled_activities_full_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectiononequestions',
            name='skilled_activities_part_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectiononequestions',
            name='standing_full_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectiononequestions',
            name='standing_part_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectiononequestions',
            name='strenuous_activities_full_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectiononequestions',
            name='strenuous_activities_part_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectiononequestions',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sectiononequestions',
            name='walking_paces_full_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectiononequestions',
            name='walking_paces_part_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectiononequestions',
            name='work_involves_seasonal_activity',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sectionthreequestions',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sectiontwoquestions',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='health_status',
            field=models.CharField(choices=[('bp', 'BP'), ('weight', 'Weight'), ('bmi', 'BMI'), ('diastolic', 'Diastolic')], max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to='users.customuser'),
        ),
    ]
