# Generated by Django 4.0.4 on 2024-05-20 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='phone_number',
        ),
    ]
